version: 2
updates:
  - package-ecosystem: nuget
    directory: "/"
    schedule:
      interval: daily
    assignees:
      - thnetii/organization
  - package-ecosystem: gitsubmodule
    directory: "/"
    schedule:
      interval: daily
    assignees:
      - thnetii/organization
