name: $(Date:yyyy-MM-dd)-build-$(Rev:r)
jobs:
- job: Windows
  pool: Hosted VS2017
  steps:
  - template: azure-pipelines/dotnetcore.steps.yml
    parameters:
      configuration: $(BuildConfiguration)
      runtimeId: win-x64
      enableCodeCoverage: true
      selfContained: true
