name: $(Date:yyyy-MM-dd)-build-$(Rev:r)
jobs:
- template: dotnetcore.job.yml
  parameters:
    jobName: windows
    jobDisplayName: Windows (x64)
    pool: Hosted VS2017
    configuration: $(BuildConfiguration)
    runtimeId: win-x64
    enableCodeCoverage: true
    selfContained: true
    artifactPrefix: thnetii-dotnet-common
