name: $(Date:yyyy-MM-dd)-build-$(Rev:r)
resources:
  repositories:
  - repository: buildtemplates
    type: GitHub
    name: thnetii/azure-pipelines
jobs:
- job: Windows
  pool: Hosted VS2017
  steps:
  - template: dotnetcore.steps.yml@buildtemplates
    parameters:
      configuration: $(BuildConfiguration)
      runtimeId: win-x64
      enableCodeCoverage: true
      selfContained: true
