name: $(Date:yyyy-MM-dd)-rev$(Rev:r)
jobs:
- template: azure-pipelines.dotnetcore.buildJob.yml
  parameters:
    jobIdSuffix:                DebugConfiguration
    jobDisplayName:             Debug Configuration
    condition:                  ne(variables['SkipConfigurationDebug'], 'true')
    addStaticConfigurationArguments:  --configuration Debug
    addVarConfigurationArguments:     $(AddDebugArguments)
    arftifactNameSuffix:        debug
- template: azure-pipelines.dotnetcore.buildJob.yml
  parameters:
    jobIdSuffix:                ReleaseConfiguration
    jobDisplayName:             Release Configuration
    condition:                  ne(variables['SkipConfigurationRelease'], 'true')
    addStaticConfigurationArguments:  --configuration Release
    addVarConfigurationArguments:     $(AddReleaseArguments)
    arftifactNameSuffix:        release
