parameters:
  jobIdSuffix:
  jobDisplayName:
  condition:                  true
  allProjects:                '*.sln'
  sourceProjects:             '[Ss]rc/*/*.csproj'
  testProjects:               '[Tt]est/*/*.csproj'
  commonArguments:            '-p:BuildId=$(Build.BuildId) "-logger:THNETII.AzureDevOps.MSBuild.Logger.AzureDevOpsLogger,$(Build.SourcesDirectory)/ci/THNETII.AzureDevOps.MSBuild.Logger/THNETII.AzureDevOps.MSBuild.Logger.dll"'
  addStaticConfigurationArguments:
  addVarConfigurationArguments:
  arftifactNameSuffix:
  publishWebProjects:         false
jobs:
- job: build${{ parameters.jobIdSuffix }}
  displayName:  ${{ parameters.jobDisplayName }}
  condition:    ${{ parameters.condition }}
  steps:
  - template: download-azuredevops-msbuild-logger.yml
  - task: DotNetCoreCLI@2
    displayName:  dotnet restore ${{ parameters.addStaticConfigurationArguments }}
    inputs:
      command:    custom
      custom:     restore
      projects:   ${{ parameters.allProjects }}
      arguments:  ${{ parameters.commonArguments }} $(AddCommonArguments) $(AddRestoreArguments)
  - task: DotNetCoreCLI@2
    displayName:  dotnet build ${{ parameters.addStaticConfigurationArguments }}
    inputs:
      command:    build
      projects:   ${{ parameters.allProjects }}
      arguments:  ${{ parameters.commonArguments }} $(AddCommonArguments) ${{ parameters.addStaticConfigurationArguments }} ${{ parameters.addVarConfigurationArguments }} $(AddBuildArguments)
  - task: DotNetCoreCLI@2
    displayName:  dotnet test ${{ parameters.addStaticConfigurationArguments }}
    condition:    ne(variables['SkipStepTestRun'], 'true')
    inputs:
      command:    test
      projects:   ${{ parameters.testProjects }}
      arguments:  ${{ parameters.commonArguments }} $(AddCommonArguments) ${{ parameters.addStaticConfigurationArguments }} ${{ parameters.addVarConfigurationArguments }} $(AddTestArguments)
      publishTestResults: true
  - task: DotNetCoreCLI@2
    displayName:  dotnet pack ${{ parameters.addStaticConfigurationArguments }}
    inputs:
      command:    custom
      custom:     pack
      projects:   ${{ parameters.sourceProjects }}
      arguments:  --output $(Build.ArtifactStagingDirectory)/${{ parameters.arftifactNameSuffix }} ${{ parameters.commonArguments }} $(AddCommonArguments) ${{ parameters.addStaticConfigurationArguments }} ${{ parameters.addVarConfigurationArguments }} $(AddPackArguments)
  - task: DotNetCoreCLI@2
    displayName:  dotnet publish ${{ parameters.addStaticConfigurationArguments }}
    inputs:
      command:            publish
      projects:           ${{ parameters.sourceProjects }}
      arguments:          --output $(Build.ArtifactStagingDirectory)/${{ parameters.arftifactNameSuffix }} ${{ parameters.commonArguments }} $(AddCommonArguments) ${{ parameters.addStaticConfigurationArguments }} ${{ parameters.addVarConfigurationArguments }} $(AddPublishArguments)
      publishWebProjects: ${{ parameters.publishWebProjects }}
      zipAfterPublish:    false
  - task: PublishBuildArtifacts@1
    displayName: Upload Published Artifacts
    inputs:
      PathtoPublish:  $(Build.ArtifactStagingDirectory)/${{ parameters.arftifactNameSuffix }}
      ArtifactName:   $(System.TeamProject)-${{ parameters.arftifactNameSuffix }}
    continueOnError: true
